%YAML:1.0

CreateSingleObject: 0

# [new add]
frame_by_frame: 1  # 1: True, 0: False
Tracking.frame_by_frame: 1  # 1: True, 0: False

System.mode: RGBD
System.output: KeyFrameTrajectoryRGBD.txt

# System.mode: MONOCULAR
# System.output: KeyFrameTrajectoryMONO.txt

System.LocalMappingInSameThread: 1


# Camera frames per second
Camera.fps: 30.0

# IR projector baseline times fx (aprox.)
Camera.bf: 10.0

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
# ThDepth: 40.0
ThDepth: 40.0

# Deptmap values factor
# DepthMapFactor: 5000.0
DepthMapFactor: 5208.0 # same as Camera.scale


DetectorConfigPath: configs/config_tum_fr2_dishes.json
Objects.maskErrosion: 5


System.UseEllipsoldPoseForDSP.Open: 1
Running.skip_num: 5
Running.total_ratio: 1.0

flip_sample_num: 4


SemanticPrior.PriorD: 1
SemanticPrior.PriorE: 1

# when >0, filter using dis to groundplane
Visualization.Map.Filter.DisThresh: 2.3

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 4000
# ORB Extractor: Scale factor between levels in the scale pyramid
ORBextractor.scaleFactor: 1.2
# ORB Extractor: Number of levels in the scale pyramid
ORBextractor.nLevels: 8
# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast
ORBextractor.iniThFAST: 12
ORBextractor.minThFAST: 7

# [Dataset Path]
Dataset.Type: "TUM"
Dataset.Path.Root: "/home/lj/Documents/dataset/TUM/rgbd_dataset_freiburg2_dishes"
Dataset.Path.Map: "./dataset.pcd"

Dataset.UseGroundtruth: 1

# Set zero to close.
#Dataset.Timestamp.Start: 1311873055.455915
#Dataset.Timestamp.Start: 1311873055.788069
Dataset.Timestamp.Start: 0
Dataset.Timestamp.End: 0
# deg
Optimizer.Edges.3DConstrain.PlaneAngle.Sigma: 100
EllipsoidExtractor.SupportingPlaneFilter.DisThresh: 0.02

Dataset.Jumpframe: 5
Dataset.Jumpframe.exp: 3

# -----------------------------
#   Monocular Infer
# -----------------------------
System.MonocularInfer.Open: 1

Dataset.Path.PriTable: "./config/pritable.txt"

MonocularInfer.Init.Dis: 5
# Prior weight
SemanticPrior.Weight: 1
# Ground Plane Contrain weight
SemanticPrior.GroundWeight: 2

# ------------------------------
#  Probabilistic Data Association
# ------------------------------
#

# 创建新物体所需满足的概率
DataAssociation.DPAlpha: 0.1
DataAssociation.PlaneError.DisSigma: 0.1

# ------------------------------------
#  Single-frame ellipsoid estimation
# ------------------------------------
# Pointcloud segmentation parameters
EllipsoidExtraction.Euclidean.ClusterTolerance: 0.1
EllipsoidExtraction.Euclidean.MinClusterSize: 5
EllipsoidExtraction.Euclidean.CenterDis: 0.5

EllipsoidExtractor.Rotation.NormalVoter.KSearchNum: 35
EllipsoidExtractor.MinNeighborsInRadius: 40
EllipsoidExtractor.StatisticalOutlierRemoval.MeanK: 50

Optimizer.SLAM.mode: 1

# weights of 3d, 2d edges in optimization
Optimizer.Edges.3DEllipsoid.Scale: 0.01
Optimizer.Edges.2D.Scale: 1
Optimizer.PartialObservation.Open: 1

Optimizer.Edges.2DConstrain.Close: 0
Optimizer.Edges.3DConstrain.Close: 0

Optimizer.NonparametricDA.Num: 1
Optimizer.Optimize.Num: 5
# ------------------------------
#  Symmetry Estimation
# ------------------------------
# Whether open symmetry estimation
EllipsoidExtraction.Symmetry.Open: 0

# Downsample grid size. Extremely influence the time and efficiency.
EllipsoidExtraction.Symmetry.GridSize: 0.1

# Parameters for symmetry probability
SymmetrySolver.Sigma: 0.1

# ----------------------------------
# Symmetry types of semantic labels
# ----------------------------------
  
# Please see the definitions in the function:
# EllipsoidExtractor::LoadSymmetryPrior()

# -------------------------------
# Ground Plane Extraction
# -------------------------------
Plane.MinSize: 100
Plane.AngleThreshold: 10.0
Plane.DistanceThreshold: 0.05
Plane.MannualCheck.Open: 1

# Mannual set
Plane.Groundplane.param: !!opencv-matrix
  rows: 1
  cols: 4
  dt: d
  data: [0.00973847, 0.00468032,   0.999831,  -0.742722]
#   data: [-0.00853887,   -0.978731,   -0.204972,    0.205993]

# Whether use the normal of the groundplane to constrain the ellipsoid
Optimizer.Edges.GravityPrior.Open: 1
Optimizer.Edges.GravityPrior.Scale: 100

# ------------------------------
# Other Parameters
# ------------------------------
# Bounding box filter
Measurement.Border.Pixels: 30
Measurement.LengthLimit.Pixels: 0
Measurement.Probability.Thresh: 0

# A observation will only be valid when the robot has a change of view.
# Close it to consider every observations.
Tracking.KeyFrameCheck.Close: 1

# Visualization
Visualization.Builder.Open: 1
Visualization.Builder.Global.Open: 1

#--------------------------------------------------------------------------------------------
# Camera Parameters. 
#--------------------------------------------------------------------------------------------

# Camera calibration and distortion parameters (OpenCV) 
Camera.fx: 520.908620
Camera.fy: 521.007327
Camera.cx: 325.141442
Camera.cy: 249.701764

# 此处畸变参数暂时未被系统所使用!
Camera.k1: 0.231222
Camera.k2: -0.784899
Camera.p1: -0.003257
Camera.p2: -0.000105
Camera.k3: 0.917205

Camera.width: 640
Camera.height: 480

Camera.scale: 5208.0
#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2
Viewer.CameraSize: 0.1
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500
Viewer.InverseCameraY: 0
